### ISSUE TITLE
`Format slug` incorrectly converting accented characters

### ISSUE THREAD

**Issue by BenTangible** [TangibleInc/template-system#118]
Commit a7af4a1 was added a few months ago to convert accented characters to non-accented ones when saving a template slug and when using `<Format slug>`. I'm pretty sure this worked when it was first released, but it was just [reported on the forum](https://tangibletalk.com/t/issue-with-template-names-that-include-an-em-dash/878/13) that while this does still work for templates, the `Format` tag isn't properly converting things to slugs (e.g. `é` becoming `%c3%` instead of `e`).

**Comment by eliot-akira** [comment]
Ah, I see. I checked and `<Format slug>` is not using the function `format\slugify()` in the Framework, which was updated in that [commit](https://github.com/TangibleInc/template-system/commit/a7af4a1e258ba63ee620ab94847e67f6c39f5632). This function is what's used to generate a post slug from title when a template is saved. So the commit solved #96, but the issue with accented characters remained with `<Format slug>`.

It was a simple fix (commit https://github.com/TangibleInc/template-system/commit/22cf7247ba33ef8c0d98580cf519d45f9c4d4965) but - looking over the code for the `Format` tag, in [the folder `language/format`](https://github.com/TangibleInc/template-system/tree/main/language/format), I notice there's unfinished work where I'd started consolidating all the formatting functions into a general-purpose **Format module in the Framework** [in `framework/format`](https://github.com/TangibleInc/template-system/tree/main/framework/format).

I'll create an issue as a reminder:

- #119

---

Oh, in the `Format` tag function, I see there's an undocumented attribute `count`. It was added to count the number of items in a list, but also supports counting characters in a string (text).

Recently I was reading your exchange in the forum about creating an excerpt:

- [How to limit maximum characters with ‘…’ after](https://tangibletalk.com/t/how-to-limit-maximum-characters-with-after/1239)

We keep coming back to this topic of custom excerpts, so I understand there's a need for a better way to do things. This `<Format count>` looks like it could help in that direction, for checking if a string needs to be trimmed.
