### ISSUE TITLE
ACF Text Area Field - New Lines Setting

### ISSUE THREAD

**Issue by zackpyle** [TangibleInc/template-system#134]
When outputting ACF values, the docs say for the basic fields that <Field> tag will work for the following tags:
```
Text
Textarea
Number
Email
URL
Password
```

But the `Field` tag doesn't respect the ACF Text Area field type's "New Lines" setting. 

If it is set to "Automatically add paragraphs" or "Automatically add <br>" it still just outputs the text without any paragraphs or lines breaks.

I would suggest adding a new Content Field `<Field acf_textarea=field_name />` to take in these settings so they can be output on the frontend

**Comment by eliot-akira** [comment]
Thank you for making a note of this. There is actually an `acf_textarea` attribute already, which lets ACF format the value based on field settings - but I see it hasn't been documented yet.

- https://docs.loopsandlogic.com/integrations/acf#basic-fields

I imagine there are similar format settings for other field types in that list.

- [ ] Text
- [x] Textarea
- [ ] Number
- [ ] Email
- [ ] URL
- [ ] Password

These will need their own `acf_` attribute, so the `Field` tag can pass the value to ACF to process.

The reason why this is necessary: given only a field name, the `Field` tag doesn't know what field type it is (or that it's managed by ACF). To check automatically it would need to consult ACF-specific post type(s), which is inefficient to do every time.

Anyway, I think it will be simpler to understand and more clear in the documentation if all ACF field types had a corresponding `Field` tag attribute. That way the field value will always be processed by ACF, to apply formatting and other field settings.

**Comment by zackpyle** [comment]
Great. Yes, `acf_textarea ` worked for me!

I checked and the other Basic fields don't seem to have any settings that affect the frontend like textarea did.

Thanks Eliot!

**Comment by eliot-akira** [comment]
Good to know! Thanks for confirming about the other field types.
