### ISSUE TITLE
Forminator form Data not seen by Loops & Logic

### ISSUE THREAD

**Issue by ghen-arvesu** [TangibleInc/template-system#143]
Hi @eliot-akira 

[Forminator form Data is not showing using Loops & Logic](https://tangibletalk.com/t/submitted-data-not-seen-by-loops-logic/1301) can you take a look? Thank you!

**Comment by GabrielGallagher** [comment]
@ghen-arvesu we don't even know if this is an issue, or whether it can be replicated. We don't even know what code the guy tried. I think there are some steps missing before we report this is a problem or meaningfully investigate.

**Comment by ghen-arvesu** [comment]
ok @GabrielGallagher will close and create a task once he responded. Thanks!
