### ISSUE TITLE
4.X beta breaks scripts loaded in via an L&L template in the Document Foot position

### ISSUE THREAD

**Issue by GabrielGallagher** [TangibleInc/template-system#38]
![image](https://github.com/TangibleInc/template-system/assets/3526779/9ef3c72e-a08d-4ea6-b8c0-b6b160bea500)

See https://discourse.tangible.one/t/call-for-l-l-4-0-beta-testers/1169

**Comment by eliot-akira** [comment]
This was an issue on the user's site, caused by loading two different versions of jQuery.
