### ISSUE TITLE
Auto-indent not working in CodeMirror 6

### ISSUE THREAD

**Issue by BenTangible** [TangibleInc/template-system#43]
@eliot-akira not sure where to put this since all I can find is a deprecated CM5 repo on GitHub and an Editor repo on Bitbucket that hasn't been touched in months. Feel free to move/recreate this issue if there's a more relevant location for it.

I was playing around with the CM6 editor today and I realized that the `shift + tab` shortcut doesn't work and isn't documented in the editor's help menu. When I try it, it acts like the `ctrl + [` dedent shortcut. Since auto-indentation is my most-used shortcut personally, it'd be great to look into getting that re-implemented.

Thanks!

**Comment by BenTangible** [comment]
I just noticed that there's a `ctrl + alt + f` shortcut to auto-beautify the document which mostly works. The downside is it affects the whole document and adds line breaks. It'd be great to have slightly more control to just auto-indent while keeping certain lines minified for compactness/legibility.

**Comment by eliot-akira** [comment]
Thanks for making a note of this. Yes, this is the right place to create issues for the new editor.

For now, you can use `ctrl + alt + f` to format the whole template. (Oh, you just commented about it.) However, there is a known issue:

- #5

**Comment by BenTangible** [comment]
Adding a note here about the `ctrl + alt + f` solution: it seems that this automatically handles tag capitalization in addition to indentation. I haven't tested this across all tags, but it seems not all of L&L's dynamic tags are accounted for. For example, If you put this in a template and hit `ctrl + alt + f`, it will convert `Map` to `map`:

```html
<Map items>
  <Key one>One</Key>
  <Key two>Two</Key>
  <Key three>Three</Key>
</Map>
```

**Comment by eliot-akira** [comment]
OK, I created an overview of issues related to the formatter, all of which will be solved by creating our own HTML formatter that can be fully customized.

- #67

As you can see there, I created separate issues for everything we've discussed so far, so I'll close this current issue #43 in favor of those.
