### ISSUE TITLE
Pagination breaks in v4.0.X

### ISSUE THREAD

**Issue by GabrielGallagher** [TangibleInc/template-system#45]
From the Facebook group, a user reports:
"I have a site that I set up last month using pagination, and it was working fine. Got a report this morning that the pagination isn't there anymore on two templates...but I looked at the templates and the pagination code is still there.
Looking at the rendered page HTML, it shows the pagination div, just empty - no content between the div open/close tags.
Is this a bug introduced by the 4.0 release? I updated to the point release and same issue is showing with that too.

<PaginateFields>, however, does work in the same context

Just looked in the new preview tab for the templates, and pagination doesn't render there either."

**Comment by eliot-akira** [comment]
> it shows the pagination div, just empty - no content between the div open/close tags.

I did a quick test with pagination, and so far things are working. It looks like part of the user's comment got cut off there:

> , however, does work in the same context

That means the simple use case works, so in the other pagination template they must be doing something different which triggers the issue.

Would it be possible to get an example of the template with the issue?

**Comment by BenTangible** [comment]
> , however, does work in the same context

Looks like the tag got removed. The user was saying that `<PaginateFields>` works, but `<PaginateButtons />` does not. I just tested this and confirmed that pagination works on the front end so you're right that there must be something unique going on in other the user's template or their site. I've asked for more details.

I did however confirm that pagination buttons don't appear to work in the new preview window.

![image](https://github.com/TangibleInc/template-system/assets/113368575/85c93fe1-1d17-4bf3-9286-21a3ec74ab6f)

**Comment by eliot-akira** [comment]
Ah yes, you're right, the Preview pane doesn't yet support tags that require additional script/style. This will be solved with the "module loader" (still a work in progress), which is used in page builder integrations. Every time the preview is refreshed, it checks and fetches required assets as needed. I've created an issue as a reminder:

- #47 

Thanks for digging into the issue from different angles, very helpful to narrow down the cause - and following up with the user about their template. I'll continue testing things out to see what I can find.

**Comment by jfacemyer** [comment]
I'm the OP from FB.

So, I just pared down my code to be bare minimum to see if it's something with the code, but this exhibits the same issue:

`<Loop type=blog count=-1 paged=2>
      <a href="{Field url}"><Field title /></a>    
</Loop>
<PaginateButtons scroll_top=true />`

I'm doing some testing now to check other plugin conflicts.

**Comment by jfacemyer** [comment]
Ok, so just tested on a completely different site (because it has a bunch of posts to test with) but getting the same issue. Loop data shows, no pagination.

Going to try on a site with no other plugins, but I have to set one up with some test posts first.

**Comment by jfacemyer** [comment]
Ok, so looks like the problem is a conflict with the Divi theme :/

I've been using the plugin on several Divi sites for the last several months/year without a problem, looks like 4.0 introduced some conflict. How can I help debug? I'd be happy to set up access to a site for you.

Also, any issue with downgrading sites temporarily until there's a fix?

**Comment by jfacemyer** [comment]
Confirming that downgrading to 3.3.1 fixes the issue (temporarily).

As I've got this on an important production site that just launched, I'd love to help with finding the problem so a fix can be made ASAP. I know I've got no right to demand anything, and I appreciate all the work you're putting in already. However, I imagine you'll want a fairly well-used theme like Divi to not be a blocker for users.

Just tell me what I can do to help.

**Comment by jfacemyer** [comment]
Anything I can do to help out with debugging this?

**Comment by GabrielGallagher** [comment]
Since this seems to be a general compatibility issue with Divi rather than something specific to your setup, no additional information is needed. Of course if you'd like to contribute a fix you're welcome to submit a pull request. If not we'll just have to wait until the team has time to take a look at it.

**Comment by jfacemyer** [comment]
Ok. A lot of projects ask for some sort of additional info for debugging when reporting an issue, so I just wanted to be proactive :)

Thanks! I love the project!

**Comment by eliot-akira** [comment]
Hi @jfacemyer, thank you for the feedback. L&L version 4.0.2 has been released, including an improvement in how the AJAX script is loaded for the paginator.

Could you see if that resolves the issue?

**Comment by jfacemyer** [comment]
Sweet! I'll try it out!

**Comment by jfacemyer** [comment]
Quick test shows on my dev site that it works on the front end (still not the preview pane, but that sounds like it's a separate known issue). I'll check on the production site that was broken.

**Comment by jfacemyer** [comment]
Awesome! Everything looks good here!

You guys rock! Thanks for taking care of this. I find L&L to be an invaluable tool, I'm using it on almost every site I build these days, and adding it to some older ones!

**Comment by eliot-akira** [comment]
That's great to hear it's been solved. Thank you for the kind words! Please feel free to report any issues or feature requests in this repository.
