### ISSUE TITLE
Exclude Current Post in an ACF Relationship Loop

### ISSUE THREAD

**Issue by GabrielGallagher** [TangibleInc/template-system#51]
<Loop> query param of exclude isn’t working in combination with an ACF relationship <Loop>
 From the forum: https://discourse.tangible.one/t/exclude-current-post-in-an-acf-relationship-loop/1186

**Comment by BenTangible** [comment]
I think this "issue" is broader than just the `exclude` parameter and I've seen it come up several times on the forum. As far as I can remember, when I tested this, the ACF relationship loop, like other ACF loop types, was its own loop type and therefore didn't accept any additional query parameters. This kinda makes sense.

I've suggested to a [couple](https://discourse.tangible.one/t/acf-relationship-loop-orderby-sort-using-event-date-field/770/5) [users](https://discourse.tangible.one/t/acf-repeater-loop/938/5) that they could fix this by just using a post loop instead.

```
<Loop post_type=post id="{Field acf_relationship_field_name}" exclude=123>
```

I haven't tested this exact approach but I imagine it would work.

Would it be possible to make the ACF relationship loop simply act just like a post loop with specified IDs? Doing something like that could solve this recurring confusion where people try to add query parameters to ACF relationship loops.

**Comment by BenTangible** [comment]
Some thoughts to highlight from [the forum thread](https://discourse.tangible.one/t/exclude-current-post-in-an-acf-relationship-loop/1186/14):

> _**benjamin**_
> My gut feeling is that a relationship field loop is just looping through the values in the field and isn’t actually making a query. If that’s actually the case, then it wouldn’t make sense for it to accept query parameters, since that would “force” the relationship loop type to act as a query, making it less efficient than it is currently.

> **_zack_**
> As for fixing going forward, we can of course apply the same query params to the L&L syntax but do different things behind the scenes instead of forcing it into a query.
>
> So doing `exclude` on a `<Loop acf_relationship=field_name>` could just do a separate function on the backend to remove that post from the array without “forcing” it into a loop query?

Just doing "different things behind the scenes" should be easy peasy, right? 😜
