### ISSUE TITLE
Formatter: Prevent changing capitalization

### ISSUE THREAD

**Issue by eliot-akira** [TangibleInc/template-system#66]

**Comment by ghen-arvesu** [comment]
Hey @eliot-akira 

I also seem to have a related problem where <Template... > gets minimized to <template ..> when format is applied

 for example:
 Original
![image](https://github.com/TangibleInc/template-system/assets/81432112/137d1e87-8234-4cac-9760-f4d26c44b138)


Formatted:
![image](https://github.com/TangibleInc/template-system/assets/81432112/de2a2682-a6a2-4d16-b7fa-e5a485640f00)

thanks

**Comment by eliot-akira** [comment]
Thanks for confirming the issue. The current HTML formatter using [Prettier](https://github.com/prettier/prettie) has several related issues because it's too big and complex to customize for our template language syntax. These will be solved by:

- #67

**Comment by eliot-akira** [comment]
Resolved by:
- #67
