### ISSUE TITLE
Ensure templates always have a universal ID assigned, during post save and before exporting

### ISSUE THREAD

**Issue by eliot-akira** [TangibleInc/template-system#69]
> some templates are not getting assigned a universal ID for some reason, causing them to be created as duplicates during import

From: https://discourse.tangible.one/t/import-process-creating-duplicate-templates-styles/1195/3

Notably:

> using the CTRL+S shortcut for saving templates removes the UID from the template

**Comment by GabrielGallagher** [comment]
It sounds like @juliacanzani ran into a similar issue while trying to launch a website that required importing templates where universal IDs would get wiped which she can potentially expand on and give us a path to reproduce. This doesn't seem like an isolated incident.

**Comment by eliot-akira** [comment]
This should be solved now, I've added logic to ensure all templates have a universal ID assigned on post save, as well as before exporting.

If Julia is still experiencing the issue with the next L&L version, we can reopen this issue or create a new one.
