### ISSUE TITLE
Tangible Template block: Remember the selected saved template

### ISSUE THREAD

**Issue by BenTangible** [TangibleInc/template-system#76]
When a Tangible Template block is added to a page, it's possible to enter markup inline within the editor. Even if you switch over to the "saved template" tab of the block and select a template, you can always switch back to the editor view to see any manual markup you might have added there. The contents of the editor are never lost even if they aren't being displayed on the front end.

However, the opposite does not seem to be true. If you select a saved template, then switch to the inline editor tab and back to the saved template tab, your saved template selection is lost and it instead selects the first template by default. It would be better if the Tangible Template block could remember the selected saved template even when switching to the editor.

**Comment by eliot-akira** [comment]
Solved by https://github.com/TangibleInc/template-system/commit/aada85ddfa19831109dfa1d0ffd503dcaa2e0f09
