### ISSUE TITLE
Loop `count` attribute not working on list loop type

### ISSUE THREAD

**Issue by BenTangible** [TangibleInc/template-system#81]
Unless I was mistaken when I wrote [the section of the docs on loop attributes](https://docs.loopsandlogic.com/dynamic-tags/loop/#attributes-1), "attributes can be used for all loop types to modify the output of a loop."

If that's true (or supposed to be true), then I just noticed a bug whereby the `count` attribute doesn't do anything when used on a list loop. 

```html
<List numbers>
  <Item>One</Item>
  <Item>Two</Item>
  <Item>Three</Item>
  <Item>Four</Item>
  <Item>Five</Item>
</List>

<ul>
  <Loop list="numbers" count="3">
    <li><Field /></li>
  </Loop>
</ul>
```

Result:

> - One
> - Two
> - Three
> - Four
> - Five

**Comment by eliot-akira** [comment]
Solved in https://github.com/TangibleInc/template-system/commit/c98ac106f0a6653fa50a37933693aa284de7c4a2
