### ISSUE TITLE
ACF Date field types: Use default format from ACF field setting instead of site settings

### ISSUE THREAD

**Issue by eliot-akira** [TangibleInc/template-system#89]
From #70

> ..so that it displays the "return format " specified in the ACF settings:

![image](https://github.com/TangibleInc/template-system/assets/113368575/51e29edd-6cbc-4f36-9e25-065d88504076)

This will break backward compatibility, but it seems logical that ACF field setting has higher priority than site settings.

**Comment by eliot-akira** [comment]
@BenTangible In commit [405fbf5](https://github.com/TangibleInc/template-system/commit/405fbf5d3c34be873f17c5db5c83c31948044121), I've overhauled how ACF date field types are formatted.

Now they all get the default format from ACF field setting for "return value". Date format from Settings -> General -> Date Format is no longer taken into consideration.

A disadvantage is that the user must now specify the desired format for every Date field in its settings, instead of changing the default format all at once from site settings. This change also breaks backward compatibility, though from our recent discussion I think some of it was not working correctly anyway.

To summarize the changes:

- Date field: `Y-m-d` -> From site settings -> From field settings (default `d/m/Y`)
- Date/time field: `Y-m-d H:i:s` -> From field settings (default `d/m/Y g:i a`)
- Time field: `H:i:s` -> From field settings (default `g:i a`)

There's a reason why the original formats were the way they were (basically [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)), because ACF's date formatting makes the value ambiguous (for example `d/m/Y` versus `m/d/Y`), especially when combined with our own date formatting. The new logic gets the raw value from ACF and applies default formatting based on field settings, with all formatting handled by our Date module.

I've tested all permutations of the above fields with and without `format` and `locale` attributes, but I'd appreciate it if you can confirm that the new behavior is correct - and that it's what we really want.

**Comment by BenTangible** [comment]
Tested the different permutations on my end and it all works as I'd expect.

> ACF's date formatting makes the value ambiguous

HARD agree, haha! [#Y-m-dMasterRace](https://xkcd.com/1179/)

Ultimately this is just an ACF failure and L&L should respect it. The real solution is that the default return format in ACF should be "use site date format."

**Comment by eliot-akira** [comment]
Thanks for confirming the new change, it will ship in version `4.1.0`.
