### ISSUE TITLE
ACF group and flexible content fields broken in 4.1.0/4.1.1

### ISSUE THREAD

**Issue by BenTangible** [TangibleInc/template-system#94]
@eliot-akira, thanks for your super fast work getting those other issues fixed!

I've got two more ACF fields for you to look into, one of which was [reported on the forum](https://discourse.tangible.one/t/issue-with-acf-group-in-v4-1-1/1217). It seems that ACF group fields were also broken in the update to 4.1.0. The template below worked in previous versions but doesn't work in the latest version (including 4.1.1).

```html
<Loop acf_group=group_field>
  <Field group_text />
</Loop>
```

I tested several other ACF field types that use the `Loop` tag (select, file, link, post, relationship, taxonomy, user, gallery, flexible) and they all seemed to work except for the flexible content field, so this template didn't work either:

```html
<Loop acf_flexible="flexible_field">
  <Field flexible_text />
</Loop>
```

**Comment by eliot-akira** [comment]
Much appreciated, will be solved shortly.
